"use client"

import * as React from "react"
import { Navbar } from "@/components/layouts/Navbar"
import { Footer } from "@/components/layouts/Footer"
import { useBookmarks } from "@/components/providers/BookmarkProvider"
import { TOOLS, CATEGORIES, AI_SKILLS } from "@/data/mock"
import { getLocalizedCategory, getLocalizedTool } from "@/lib/localizeData"
import { useLocale, useTranslations } from "next-intl"
import { Link } from "@/i18n/routing"
import { Card, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/Card"
import { Badge } from "@/components/ui/Badge"
import { Button } from "@/components/ui/Button"
import { ToolLogo } from "@/components/ui/ToolLogo"
import { BookmarkButton } from "@/components/ui/BookmarkButton"
import { Copy, Download, Trash2, Layers, ExternalLink, ArrowRight, Check, Code, FileText, Settings, Terminal, Sparkles } from "lucide-react"

export default function StackPage() {
  const locale = useLocale()
  const isId = locale === "id"
  const tNav = useTranslations("Navbar")
  const { bookmarks, clearBookmarks, count } = useBookmarks()

  const [activeTab, setActiveTab] = React.useState<"cursor" | "claude" | "mcp" | "markdown">("cursor")
  const [copied, setCopied] = React.useState(false)

  const savedTools = TOOLS.filter(t => bookmarks.includes(t.id)).map(t => getLocalizedTool(t, locale))

  // Group tools by categories
  const categoriesCovered = Array.from(new Set(savedTools.map(t => t.categoryId)))
  const openSourceCount = savedTools.filter(t => t.isOpenSource).length

  // Generate .cursorrules content
  const generateCursorRules = () => {
    if (savedTools.length === 0) return "# Simpan alat AI ke Stack Anda untuk membuat .cursorrules otomatis"
    
    return `# .cursorrules - Custom AI Developer Stack
# Generated by Awesome AI Tools (https://awesome-ai-tools.local)
# Date: ${new Date().toISOString().split("T")[0]}

# 1. ACTIVE AI TECH STACK
${savedTools.map(t => `- ${t.name}: ${t.description} (Category: ${CATEGORIES.find(c => c.id === t.categoryId)?.name || "General"})`).join("\n")}

# 2. GENERAL CODING STANDARDS & WORKFLOW
- Always write clean, maintainable, type-safe code with TypeScript and modern best practices.
- Prefer modular architecture, single-responsibility functions, and explicit error handling.
- Verify that imports and library versions match the active project ecosystem.

# 3. AI AGENT & PROMPT GUIDELINES
- When scaffolding components or backend logic, align with tools: ${savedTools.map(t => t.name).join(", ")}.
- Keep answers concise, actionable, and free from redundant commentary.
- Provide full, copy-paste ready code blocks with filename annotations.
`
  }

  // Generate CLAUDE.md content
  const generateClaudeMd = () => {
    if (savedTools.length === 0) return "# Simpan alat AI ke Stack Anda untuk membuat CLAUDE.md otomatis"

    return `# CLAUDE.md - AI Agent Operating Manual
# Project AI Stack generated via Awesome AI Tools

## Active Stack & Tooling
${savedTools.map(t => `### ${t.name}
- **Category**: ${CATEGORIES.find(c => c.id === t.categoryId)?.name || "General"}
- **Website**: ${t.website}
- **Description**: ${t.description}
- **Pricing**: ${t.pricing} (${t.isOpenSource ? "Open-Source" : "Proprietary"})
`).join("\n")}

## Development Philosophy
1. Focus on deterministic, test-driven implementations.
2. Avoid AI slop, bloated wrappers, and unnecessary abstractions.
3. Optimize for developer velocity and local-first inference whenever possible.
`
  }

  // Generate mcp-config.json
  const generateMcpConfig = () => {
    const mcpServers: Record<string, any> = {}

    savedTools.forEach(t => {
      const slug = t.name.toLowerCase().replace(/[^a-z0-9]/g, "-")
      mcpServers[slug] = {
        command: "npx",
        args: ["-y", `@modelcontextprotocol/server-${slug}`],
        env: {
          API_KEY: `\${${slug.toUpperCase().replace(/-/g, "_")}_API_KEY}`
        }
      }
    })

    return JSON.stringify({ mcpServers }, null, 2)
  }

  // Generate Markdown summary
  const generateMarkdown = () => {
    if (savedTools.length === 0) return ""

    return `## 🛠️ My AI Developer Stack

| Tool | Category | Pricing | Open Source | Website |
| :--- | :--- | :--- | :--- | :--- |
${savedTools.map(t => {
  const cat = CATEGORIES.find(c => c.id === t.categoryId)?.name || "General"
  return `| **${t.name}** | ${cat} | ${t.pricing} | ${t.isOpenSource ? "✅ Yes" : "❌ No"} | [Visit](${t.website}) |`
}).join("\n")}

*Generated with [Awesome AI Tools](http://localhost:3000)*
`
  }

  const getConfigText = () => {
    switch (activeTab) {
      case "cursor": return generateCursorRules()
      case "claude": return generateClaudeMd()
      case "mcp": return generateMcpConfig()
      case "markdown": return generateMarkdown()
    }
  }

  const getFilename = () => {
    switch (activeTab) {
      case "cursor": return ".cursorrules"
      case "claude": return "CLAUDE.md"
      case "mcp": return "mcp-config.json"
      case "markdown": return "ai-stack.md"
    }
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(getConfigText())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const text = getConfigText()
    const filename = getFilename()
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = filename
    link.click()
    URL.revokeObjectURL(url)
  }

  return (
    <>
      <Navbar />
      <main className="flex-1 min-h-[calc(100vh-14rem)] bg-[var(--background)] py-12">
        <div className="container mx-auto px-4 max-w-6xl space-y-10">
          
          {/* Header */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-6 border-b border-[var(--border)]">
            <div>
              <div className="flex items-center gap-2.5">
                <h1 className="text-3xl font-bold tracking-tight">
                  {isId ? "My AI Developer Stack" : "My AI Developer Stack"}
                </h1>
                <Badge variant="accent">
                  {count} {isId ? "Tersimpan" : "Saved"}
                </Badge>
              </div>
              <p className="text-sm text-[var(--muted)] mt-1.5">
                {isId
                  ? "Kelola tool AI pilihan Anda dan ekspor konfigurasi otomatis (.cursorrules, CLAUDE.md, mcp-config.json) untuk editor koding."
                  : "Manage your personalized AI stack and export automated configurations (.cursorrules, CLAUDE.md, mcp-config.json) for code editors."}
              </p>
            </div>

            {count > 0 && (
              <Button
                variant="outline"
                size="sm"
                onClick={clearBookmarks}
                className="text-red-500 hover:text-red-600 hover:border-red-500/40 gap-1.5"
              >
                <Trash2 className="w-3.5 h-3.5" />
                <span>{isId ? "Kosongkan Stack" : "Clear Stack"}</span>
              </Button>
            )}
          </div>

          {/* Stats Bar */}
          {count > 0 && (
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
              <div className="p-4 rounded-xl border border-[var(--border)] bg-[var(--surface)]">
                <span className="text-xs text-[var(--muted)] font-medium block mb-1">
                  {isId ? "Total Tools" : "Total Tools"}
                </span>
                <span className="text-2xl font-bold">{savedTools.length}</span>
              </div>
              <div className="p-4 rounded-xl border border-[var(--border)] bg-[var(--surface)]">
                <span className="text-xs text-[var(--muted)] font-medium block mb-1">
                  {isId ? "Kategori Tercover" : "Categories Covered"}
                </span>
                <span className="text-2xl font-bold">{categoriesCovered.length}</span>
              </div>
              <div className="p-4 rounded-xl border border-[var(--border)] bg-[var(--surface)] col-span-2 sm:col-span-1">
                <span className="text-xs text-[var(--muted)] font-medium block mb-1">
                  {isId ? "Open-Source Tools" : "Open-Source Tools"}
                </span>
                <span className="text-2xl font-bold text-emerald-500">{openSourceCount}</span>
              </div>
            </div>
          )}

          {/* Empty State */}
          {count === 0 ? (
            <div className="text-center py-16 px-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)] max-w-xl mx-auto space-y-4">
              <div className="w-12 h-12 rounded-xl bg-[var(--background)] text-[var(--muted)] flex items-center justify-center mx-auto border border-[var(--border)]">
                <Layers className="w-6 h-6" />
              </div>
              <div className="space-y-1.5">
                <h3 className="text-lg font-bold">
                  {isId ? "Belum Ada Tool yang Disimpan" : "No Tools Saved in Stack"}
                </h3>
                <p className="text-xs text-[var(--muted)] max-w-sm mx-auto">
                  {isId
                    ? "Jelajahi direktori dan klik ikon Bookmark pada kartu tool yang Anda sukai untuk mengumpulkannya di sini."
                    : "Explore the catalog and click the Bookmark icon on tools you love to collect them here."}
                </p>
              </div>
              <Button asChild className="gap-2 mt-2">
                <Link href="/categories">
                  {isId ? "Jelajahi Direktori Alat" : "Explore Tools Catalog"} <ArrowRight className="w-4 h-4" />
                </Link>
              </Button>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
              
              {/* Left Column: Bookmarked Tools Grid (5 cols) */}
              <div className="lg:col-span-5 space-y-4">
                <h3 className="font-bold text-sm text-[var(--foreground)]">
                  {isId ? "Daftar Alat dalam Stack" : "Stack Components"} ({savedTools.length})
                </h3>

                <div className="space-y-3 max-h-[580px] overflow-y-auto custom-scrollbar pr-1">
                  {savedTools.map(tool => (
                    <div
                      key={tool.id}
                      className="p-3.5 rounded-xl border border-[var(--border)] bg-[var(--surface)] flex items-center justify-between gap-3 group hover:border-[var(--muted)] transition-colors"
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <ToolLogo name={tool.name} website={tool.website} logo={tool.logo} size="sm" />
                        <div className="min-w-0">
                          <Link href={`/tools/${tool.slug}`} className="font-semibold text-xs text-[var(--foreground)] hover:text-[var(--primary)] truncate block">
                            {tool.name}
                          </Link>
                          <span className="text-[11px] text-[var(--muted)] truncate block">
                            {CATEGORIES.find(c => c.id === tool.categoryId)?.name} • {tool.pricing}
                          </span>
                        </div>
                      </div>

                      <div className="flex items-center gap-1.5 shrink-0">
                        <BookmarkButton toolId={tool.id} toolName={tool.name} size="sm" />
                        <a
                          href={tool.website}
                          target="_blank"
                          rel="noreferrer"
                          className="p-1 rounded text-[var(--muted)] hover:text-[var(--foreground)] transition-colors"
                        >
                          <ExternalLink className="w-3.5 h-3.5" />
                        </a>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Right Column: Automated IDE Config Generator (7 cols) */}
              <div className="lg:col-span-7 space-y-4">
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                  <h3 className="font-bold text-sm text-[var(--foreground)]">
                    {isId ? "Generator File Konfigurasi IDE" : "Automated IDE Config Generator"}
                  </h3>

                  {/* Config Type Tabs */}
                  <div className="flex items-center gap-1 p-1 rounded-lg bg-[var(--surface)] border border-[var(--border)] text-xs">
                    <button
                      onClick={() => setActiveTab("cursor")}
                      className={`px-2.5 py-1 rounded-md font-mono text-[11px] font-medium transition-colors ${
                        activeTab === "cursor"
                          ? "bg-[var(--background)] text-[var(--foreground)] shadow-xs"
                          : "text-[var(--muted)] hover:text-[var(--foreground)]"
                      }`}
                    >
                      .cursorrules
                    </button>
                    <button
                      onClick={() => setActiveTab("claude")}
                      className={`px-2.5 py-1 rounded-md font-mono text-[11px] font-medium transition-colors ${
                        activeTab === "claude"
                          ? "bg-[var(--background)] text-[var(--foreground)] shadow-xs"
                          : "text-[var(--muted)] hover:text-[var(--foreground)]"
                      }`}
                    >
                      CLAUDE.md
                    </button>
                    <button
                      onClick={() => setActiveTab("mcp")}
                      className={`px-2.5 py-1 rounded-md font-mono text-[11px] font-medium transition-colors ${
                        activeTab === "mcp"
                          ? "bg-[var(--background)] text-[var(--foreground)] shadow-xs"
                          : "text-[var(--muted)] hover:text-[var(--foreground)]"
                      }`}
                    >
                      mcp-config
                    </button>
                    <button
                      onClick={() => setActiveTab("markdown")}
                      className={`px-2.5 py-1 rounded-md font-mono text-[11px] font-medium transition-colors ${
                        activeTab === "markdown"
                          ? "bg-[var(--background)] text-[var(--foreground)] shadow-xs"
                          : "text-[var(--muted)] hover:text-[var(--foreground)]"
                      }`}
                    >
                      README
                    </button>
                  </div>
                </div>

                {/* Code Preview Box */}
                <div className="rounded-xl border border-[var(--border)] bg-zinc-950 overflow-hidden font-mono text-xs shadow-md">
                  <div className="flex items-center justify-between px-4 py-2.5 bg-zinc-900 border-b border-zinc-800 text-zinc-400">
                    <span className="font-bold text-zinc-300">{getFilename()}</span>
                    
                    <div className="flex items-center gap-2">
                      <button
                        onClick={handleCopy}
                        className="flex items-center gap-1 text-[11px] hover:text-white transition-colors cursor-pointer px-2 py-1 rounded hover:bg-zinc-800"
                      >
                        {copied ? (
                          <>
                            <Check className="w-3.5 h-3.5 text-green-400" />
                            <span className="text-green-400">Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" />
                            <span>Copy</span>
                          </>
                        )}
                      </button>

                      <button
                        onClick={handleDownload}
                        className="flex items-center gap-1 text-[11px] hover:text-white transition-colors cursor-pointer px-2 py-1 rounded hover:bg-zinc-800"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>Download</span>
                      </button>
                    </div>
                  </div>

                  <pre className="p-4 text-zinc-200 overflow-x-auto selection:bg-zinc-800 max-h-[440px] leading-relaxed custom-scrollbar">
                    <code>{getConfigText()}</code>
                  </pre>
                </div>

                <p className="text-[11px] text-[var(--muted)] leading-relaxed">
                  {isId
                    ? `Tips: Download atau salin file ${getFilename()} lalu letakkan di root directory project Anda agar editor AI (Cursor / Claude Code / Cline) langsung memahami stack tools yang Anda gunakan.`
                    : `Tip: Download or copy ${getFilename()} and place it in your project's root folder so AI agents (Cursor / Claude Code / Cline) immediately recognize your tools stack.`}
                </p>
              </div>

            </div>
          )}

        </div>
      </main>
      <Footer />
    </>
  )
}
